### ISSUE TITLE
missing typescript definitions 

### ISSUE THREAD

**Issue by OneOfOne** [xnimorz/masked-input#1]
It's missing typescript defs and my tsc was throwing a fit in strict mode, any chance you could include that?

**Comment by xnimorz** [comment]
Hello, @OneOfOne I'm thinking of adding ts defs in future.

**Comment by xnimorz** [comment]
Now, I'm changing this project from javascript to typescript. WIthin 1 or 2 months I think I'll publish the major release.

**Comment by xnimorz** [comment]
https://github.com/xnimorz/masked-input/pull/2
