### ISSUE TITLE
Warning: componentWillReceiveProps

### ISSUE THREAD

**Issue by boycce** [xnimorz/masked-input#11]
Hi, thanks for the component :+1: 

Currently i'm receiving this error with `"react": "^16.13.1"`

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> **Please update the following components: MaskInput**

**Comment by xnimorz** [comment]
Hi @boycce!

Thank you for the issue!
I think it would be better to change the component from classes to function with hooks. 
I'll change it several weeks later when I get some free time.

**Comment by xnimorz** [comment]
Hey @boycce !
Here is a commit, which should solve this issue: https://github.com/xnimorz/masked-input/commit/ff1f97317ff019bd32e9a7c258ecede3bcb82437

I'll test the component and publish the release in several days.

**Comment by xnimorz** [comment]
Hi @boycce 
Fixed and published with react-maskinput@3.1.0

**Comment by xnimorz** [comment]
Hi @boycce 
I'll close the issue as it seems to be resolved. 
Feel free to reopen it or make another one in case you have any question :)
