### ISSUE TITLE
onFocus and onBlur properties obligation

### ISSUE THREAD

**Issue by andrewdourado** [xnimorz/masked-input#15]
Is it really necessary set the properties onFocus and onBlur?

**Comment by xnimorz** [comment]
Hi, react-maskinput doesn't require onFocus and onBlur callbacks, however, you are able to set them https://github.com/xnimorz/masked-input/blob/master/packages/react-maskinput/src/index.tsx#L23-L24

But yes, it will be better to make them optional. I'll add it with the new version of the lib

**Comment by andrewdourado** [comment]
Thanks. I can send a PR if you think it interesting.

**Comment by xnimorz** [comment]
I'm going to publish a new major release with react hooks. I'll add it with this release

**Comment by xnimorz** [comment]
Thank you for the issue!
Fixed and published with `react-maskinput@3.1.0`

https://github.com/xnimorz/masked-input/blob/master/packages/react-maskinput/src/index.tsx#L23-L24

**Comment by andrewdourado** [comment]
I thank you for the updates.
