### ISSUE TITLE
export interface IInputProps

### ISSUE THREAD

**Issue by andrewdourado** [xnimorz/masked-input#16]
Is it interesting export interface IInputProps for those who use Typescript?

**Comment by xnimorz** [comment]
Hi @andrewdourado 
Yes, IInputProps is for TS interfaces. You can check It here https://unpkg.com/browse/react-maskinput@3.0.0/lib/index.d.ts

**Comment by andrewdourado** [comment]
I understand. But to use it I believe it is necessary to use `export interface IInputProps`. 
The idea is to add it to the code to define the types of the component. Something like: 
```
import { IMaskInput } from 'react-imask';

interface Props extends IInputProps {
  name: string;
}
```

**Comment by xnimorz** [comment]
Oh, yes, get it. 
Fixed and published with `react-maskinput@3.1.0`

https://github.com/xnimorz/masked-input/blob/master/packages/react-maskinput/src/index.tsx#L10

**Comment by xnimorz** [comment]
Thank you!

**Comment by andrewdourado** [comment]
I thank you for the updates.

**Comment by andrewdourado** [comment]
I thank you for the updates.
