### ISSUE TITLE
Hide special character from the beginning

### ISSUE THREAD

**Issue by andrewdourado** [xnimorz/masked-input#17]
I'm having a problem with special characters at the beginning of the field. For example:

<img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/15659599/94858003-be118200-0408-11eb-8932-fbfaaafb4dac.png">

In code: 

```
<MaskInput
     alwaysShowMask={false}
     showMask={false}
     maskChar=""
     name="telephone"
     mask="(00) 0 0000-0000"
/>
```

Is there any way to hide it?

**Comment by xnimorz** [comment]
Hi @andrewdourado 
Thank you for the issue!
At the moment this component doesn't provide such behavior. 
I'll take a look this weekends how we can add this feature

**Comment by xnimorz** [comment]
Hey @andrewdourado 
I've added a new param showStartChars to the component. It's set to false by default. This param allows hiding starting hardcoded chars:
```js
import MaskInput from 'react-maskinput';

<MaskInput showStartChars={false} mask="+7 (000) 000 00-00" size={26} />;
```
Here is a video:
https://youtu.be/IyAGuG8GvBI

Also, you can check it here:
https://xnimorz.github.io/masked-input/#section-masked-inputs

**Comment by xnimorz** [comment]
Oh, I forgot to point the version. 
It's 3.2.0, I've published the release

**Comment by xnimorz** [comment]
Hi @andrewdourado 
I'll close the issue at the moment, as the release with fixes was published. 
Feel free to reopen the issue or create a new one if you have any questions
