### ISSUE TITLE
IInputProps should extend the default props

### ISSUE THREAD

**Issue by rotexhawk** [xnimorz/masked-input#47]
It's probably a good idea to extend the default react input props instead of providing a custom type because currently if you pass valid input props such as `required` or `className` you get type error. It will still work as is because we passthrough the props anyways.

**Comment by mkeskin** [comment]
I opened a pr in here:
https://github.com/xnimorz/masked-input/pull/54

**Comment by xnimorz** [comment]
Thanks for the contribution, @mkeskin !

**Comment by xnimorz** [comment]
Published in 3.2.1

**Comment by smithki** [comment]
@xnimorz FYI 3.2.1 is missing built `/lib` files and is not tagged `latest` on NPM.
