### ISSUE TITLE
Version 3.2.1: Cannot find module 'react-maskinput' or its corresponding type declarations.

### ISSUE THREAD

**Issue by maks-io** [xnimorz/masked-input#55]
Hi guys, i don't have much time to further investigate this at the moment, but I thought I let you know that when using the latest version `3.2.1`, i receive `TS2307: Cannot find module 'react-maskinput' or its corresponding type declarations.` upon importing this lib via `import MaskInput from "react-maskinput"`. When i downgrade back to `3.2.0` everything's alright again.

**Comment by guccibase** [comment]
I also receive `Module not found: Can't resolve 'react-maskinput/lib'`

**Comment by degueba** [comment]
I also receive the same error guys: 
![image](https://user-images.githubusercontent.com/17730060/217850771-dca3d52c-6792-4b20-b368-09bfa89acbe2.png)

**Comment by xnimorz** [comment]
Hey all,

Thank you for the feedback. I appreciate it.

I'd recommend using 3.2.0 for a while, I plan to fix 3.2.1 soon. 
The reason of the bug is pretty simple, the author (me) forgot about some specific lerna behaviour ;-(

**Comment by xnimorz** [comment]
As a quick fix, I've changed the latest version back to 3.2.0, so it will be safe to use
