### ISSUE TITLE
 241/5000 pseudo-class: focus does not work in CSS

### ISSUE THREAD

**Issue by andreytmendes** [xnimorz/masked-input#6]
What's up friend !

I'm really enjoying the lib, but it is affecting the pseudo-class: CSS focus, I am applying the mask to some inputs in my form, do you know how I can solve this bug?

hug

**Comment by xnimorz** [comment]
Hi @andreytmendes 
Please check out the demo page https://xnimorz.github.io/masked-input/

Here inputs have :focus pseudo-class: 
![image](https://user-images.githubusercontent.com/1178825/79958015-1bcd9580-848b-11ea-941d-fa680690c727.png)

And they work even if I remove :focus from dev tools:
![image](https://user-images.githubusercontent.com/1178825/79958128-3e5fae80-848b-11ea-8292-5d2e739dcead.png)

If you have an example where masked-input doesn't work with focus, feel free to share it example with me :)

**Comment by xnimorz** [comment]
Hi, as I didn't get additional info, I'm going to close this issue. Feel free to reopen it or create a new one.
